"""RidersBuddy Phase 1

Revision ID: d72de655c5d4
Revises: 
Create Date: 2026-02-18 17:42:16.676700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72de655c5d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riders_name'), 'riders', ['name'], unique=True)
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waypoints_grid_x'), 'waypoints', ['grid_x'], unique=False)
    op.create_index(op.f('ix_waypoints_grid_y'), 'waypoints', ['grid_y'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('start_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('end_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['end_waypoint_id'], ['waypoints.id'], ),
    sa.ForeignKeyConstraint(['start_waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_difficulty'), 'routes', ['difficulty'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=True)
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_waypoints_route_id'), 'route_waypoints', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_waypoints_waypoint_id'), 'route_waypoints', ['waypoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_waypoints_waypoint_id'), table_name='route_waypoints')
    op.drop_index(op.f('ix_route_waypoints_route_id'), table_name='route_waypoints')
    op.drop_table('route_waypoints')
    op.drop_table('rides')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_difficulty'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_waypoints_grid_y'), table_name='waypoints')
    op.drop_index(op.f('ix_waypoints_grid_x'), table_name='waypoints')
    op.drop_table('waypoints')
    op.drop_index(op.f('ix_riders_name'), table_name='riders')
    op.drop_table('riders')
    # ### end Alembic commands ###
